---
- name: Create Homework Assignment project 
  shell: tower-cli project create --organization="{{org_name}}" --scm-type=git --scm-branch="{{scm_branch}}" --scm-url="{{ scm_url }}" --scm-update-on-launch=True -n "{{ proj_name }}"

- name: Machine Credential to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    ssh_key_data: "/root/.ssh/openstack.pem"
    username: cloud-user
    tower_verify_ssl: no 

- name: Create Inventory
  #command: |
  #  tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"
  tower_inventory:
    name: "{{ static_inventory_name }}"
    organization: "{{ org_name }}"
    state: present
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no

- name: Create Group in static inventory 
#  command: |
#    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}
  tower_group:
    name: "{{ group_name }}"
    inventory: "{{ static_inventory_name }}"
    state: present
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no

- name: Add workstation host in tower_inventory
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}" --insecure
#    tower-cli host create --name "{{ host_name }}" --inventory "{{static_inventory_name}}" 
#  tower_host:
#    name: "{{ host_name }}"
#    inventory: "{{ static_inventory_name }}"
#    state: present
#    tower_username: admin
#    tower_password: r3dh4t1!
#    tower_verify_ssl: no

- name: Associate workstation host to group 
#  command: | 
  shell: tower-cli host associate --insecure --host "{{host_name}}" --group "{{group_name}}" -u admin -p r3dh4t1!


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no
    ssh_key_data: /root/.ssh/mykey.pem
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

